"""Initial V1 schema — tenants, users, documents, chunks, jobs, evidence
chain (evidence_items, claims, claim_evidence, citations, reports), audits,
ingestion_runs.

Hand-written rather than autogenerated: no live PostgreSQL instance was
available when this revision was authored (Docker daemon was not running).
Mirrors src/models/orm.py table-for-table, column-for-column — verify with
`alembic check` against a real database before this ships, and treat any
diff `alembic check` reports as a bug in this file, not in the ORM models.

Revision ID: 0001
Revises:
Create Date: 2026-08-14
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from src.models.db_types import GUID, PortableJSON

revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tenants",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("name", sa.String(255), nullable=False, unique=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    op.create_table(
        "users",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("tenant_id", GUID(), sa.ForeignKey("tenants.id"), nullable=False),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"])

    op.create_table(
        "documents",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("tenant_id", GUID(), sa.ForeignKey("tenants.id"), nullable=True),
        sa.Column("company", sa.String(255), nullable=False),
        sa.Column("ticker", sa.String(16), nullable=False),
        sa.Column(
            "document_type",
            sa.Enum(
                "10-K",
                "10-Q",
                "8-K",
                "annual_report",
                "earnings_release",
                "investor_presentation",
                "earnings_transcript",
                "news",
                "other",
                name="document_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("filing_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("fiscal_quarter", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("supersedes_id", GUID(), sa.ForeignKey("documents.id"), nullable=True),
        sa.Column("content_hash", sa.String(64), nullable=False),
        sa.Column("raw_object_key", sa.Text(), nullable=False),
        sa.Column("raw_content_type", sa.String(128), nullable=False, server_default="text/html"),
        sa.Column(
            "ingestion_status",
            sa.Enum(
                "pending",
                "succeeded",
                "failed",
                "skipped_duplicate",
                name="ingestion_status",
                native_enum=False,
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("metadata_extra", PortableJSON, nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_documents_tenant_id", "documents", ["tenant_id"])
    op.create_index("ix_documents_company", "documents", ["company"])
    op.create_index("ix_documents_ticker", "documents", ["ticker"])
    op.create_index("ix_documents_filing_date", "documents", ["filing_date"])
    op.create_index("ix_documents_content_hash", "documents", ["content_hash"])
    op.create_unique_constraint("uq_documents_content_hash", "documents", ["content_hash"])
    op.create_index(
        "ix_documents_company_type_period",
        "documents",
        ["company", "document_type", "filing_date"],
    )

    op.create_table(
        "chunks",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("document_id", GUID(), sa.ForeignKey("documents.id"), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column(
            "chunk_type",
            sa.Enum("text", "table", name="chunk_type", native_enum=False),
            nullable=False,
            server_default="text",
        ),
        sa.Column("section", sa.String(255), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("table_title", sa.String(512), nullable=True),
        sa.Column("table_headers", PortableJSON, nullable=True),
        sa.Column("table_rows", PortableJSON, nullable=True),
        sa.Column("embedding_model", sa.String(128), nullable=True),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column("qdrant_point_id", sa.String(64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"])
    op.create_index("ix_chunks_qdrant_point_id", "chunks", ["qdrant_point_id"])
    op.create_index("ix_chunks_document_index", "chunks", ["document_id", "chunk_index"])

    op.create_table(
        "jobs",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("trace_id", sa.String(64), nullable=True),
        sa.Column("tenant_id", GUID(), sa.ForeignKey("tenants.id"), nullable=True),
        sa.Column("user_id", GUID(), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "awaiting_review",
                "succeeded",
                "failed",
                name="job_status",
                native_enum=False,
            ),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("iteration", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("max_iterations", sa.Integer(), nullable=False, server_default="5"),
        sa.Column("token_budget", sa.Integer(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cost_budget", sa.Float(), nullable=True),
        sa.Column("imputed_cost", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("insufficient_evidence", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_jobs_trace_id", "jobs", ["trace_id"])
    op.create_index("ix_jobs_tenant_id", "jobs", ["tenant_id"])

    op.create_table(
        "evidence_items",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("job_id", GUID(), sa.ForeignKey("jobs.id"), nullable=False),
        sa.Column("chunk_id", GUID(), sa.ForeignKey("chunks.id"), nullable=False),
        sa.Column("supporting_passage", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_evidence_items_job_id", "evidence_items", ["job_id"])
    op.create_index("ix_evidence_items_chunk_id", "evidence_items", ["chunk_id"])

    op.create_table(
        "claims",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("job_id", GUID(), sa.ForeignKey("jobs.id"), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(16), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_claims_job_id", "claims", ["job_id"])

    op.create_table(
        "claim_evidence",
        sa.Column("claim_id", GUID(), sa.ForeignKey("claims.id"), primary_key=True),
        sa.Column("evidence_id", GUID(), sa.ForeignKey("evidence_items.id"), primary_key=True),
    )

    op.create_table(
        "citations",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("claim_id", GUID(), sa.ForeignKey("claims.id"), nullable=False),
        sa.Column("evidence_id", GUID(), sa.ForeignKey("evidence_items.id"), nullable=False),
        sa.Column("document_id", GUID(), sa.ForeignKey("documents.id"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "accept", "rewrite", "remove", "flag", name="citation_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("rewritten_claim_text", sa.Text(), nullable=True),
        sa.Column("justification", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_citations_claim_id", "citations", ["claim_id"])
    op.create_index("ix_citations_evidence_id", "citations", ["evidence_id"])
    op.create_index("ix_citations_document_id", "citations", ["document_id"])

    op.create_table(
        "reports",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("job_id", GUID(), sa.ForeignKey("jobs.id"), nullable=False),
        sa.Column("tenant_id", GUID(), sa.ForeignKey("tenants.id"), nullable=True),
        sa.Column("draft", sa.Text(), nullable=True),
        sa.Column("final_report", sa.Text(), nullable=True),
        sa.Column("run_manifest", PortableJSON, nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_reports_job_id", "reports", ["job_id"])
    op.create_index("ix_reports_tenant_id", "reports", ["tenant_id"])

    op.create_table(
        "audits",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("job_id", GUID(), sa.ForeignKey("jobs.id"), nullable=True),
        sa.Column("tenant_id", GUID(), sa.ForeignKey("tenants.id"), nullable=True),
        sa.Column("actor", sa.String(255), nullable=False),
        sa.Column("action", sa.String(128), nullable=False),
        sa.Column("detail", PortableJSON, nullable=False, server_default="{}"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index("ix_audits_tenant_id", "audits", ["tenant_id"])
    op.create_index("ix_audits_created_at", "audits", ["created_at"])

    op.create_table(
        "ingestion_runs",
        sa.Column("id", GUID(), primary_key=True),
        sa.Column("source", sa.String(64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "partial",
                name="ingestion_run_status",
                native_enum=False,
            ),
            nullable=False,
            server_default="running",
        ),
        sa.Column("embedding_model", sa.String(128), nullable=True),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column("chunking_config_version", sa.String(64), nullable=True),
        sa.Column("documents_processed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("documents_skipped_duplicate", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("documents_failed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("parser_errors", PortableJSON, nullable=False, server_default="[]"),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )


def downgrade() -> None:
    op.drop_table("ingestion_runs")
    op.drop_table("audits")
    op.drop_table("reports")
    op.drop_table("citations")
    op.drop_table("claim_evidence")
    op.drop_table("claims")
    op.drop_table("evidence_items")
    op.drop_table("jobs")
    op.drop_table("chunks")
    op.drop_table("documents")
    op.drop_table("users")
    op.drop_table("tenants")
